ERROR:root:__init__() takes exactly 2 arguments (1 given)
INFO:root:[('id',), ('name',), ('value',)]
